// file generated by cmake to pass varaibles to source code

#ifndef  CONFIG
#define  CONFIG

#define NMR_VERSION_MAJOR @NMR_VERSION_MAJOR@
#define NMR_VERSION_MINOR @NMR_VERSION_MINOR@
#cmakedefine USE_OPENMP

#endif
