// file generated by cmake to pass varaibles to source code

#ifndef  CONFIG
#define  CONFIG

#define NMR_VERSION_MAJOR 1
#define NMR_VERSION_MINOR 0
/* #undef WIN32 */
/* #undef USE_OPENMP */

#endif
